language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh && bash -ex test.sh
env:
  - OCAML_VERSION=4.02 PACKAGE=thin_lvhd_tools PRE_INSTALL_HOOK="opam remote add thin-lvhd git://github.com/xapi-project/thin-lvhd-opam-repo && opam update -u -y"
