language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-base
    - ocaml-native-compilers
    - ocaml-compiler-libs
    - ocaml-interp
    - ocaml-base-nox
    - ocaml-nox
    - camlp4
    - camlp4-extra
    - libdevmapper-dev
env:
  - FORK_USER=talex5 FORK_BRANCH=containers OPAMYES=true OCAML_VERSION=4.02 PACKAGE=thin_lvhd_tools EXTRA_REMOTES="git://github.com/xapi-project/thin-lvhd-opam-repo" TESTS=true PINS="conduit:git://github.com/mirage/ocaml-conduit" EXTRA_REMOTES="git://github.com/xapi-project/opam-repo-dev" POST_INSTALL_HOOK="bash -eux .travis-post-install.sh"
